# Generated by Django 3.1 on 2020-08-31 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0001_squashed_0007_todoitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='user',
        ),
        migrations.DeleteModel(
            name='ToDoItem',
        ),
        migrations.DeleteModel(
            name='ToDoList',
        ),
    ]
