# Generated by Django 3.1 on 2020-08-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='priority',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
