# Generated by Django 3.1 on 2020-08-12 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0003_auto_20200812_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
