# Generated by Django 3.1 on 2020-08-12 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0005_auto_20200812_1212'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ToDoItem',
        ),
    ]
